let blogs = [["Homemade laptop, Nextcloud and possible updates to website", "This week I used my raspberry pi to make a Homemade laptop, for the case I used a cardboard box with a hinge duck taped to the back so it doesn't flop around.  I used a drawing tablet as a mouse as I had no spare mouse, the monitor is my phone conecting to the raspberry pi through <a href='https://en.wikipedia.org/wiki/Virtual_Network_Computing'>VNC</a> which is very janky and I used a massive portable charger to keep the phone and pi charged, the whole thing is really janky and I want to maybe get a 7 inch monitor for it which would work way better but, that's for the furture me.  I've found a cool new feature on Nextcloud called face recognition, I have not gotton it working though so I'll try figure that out, I suck at troubleshooting, it took like a week to figure out how to use occ, it's in the nextcloud root directory ._., there's also a map fearture which uses <a href='https://www.openstreetmap.org'>Open Street Maps</a> to show where images where taken and when and also to plot addresses of your contacts which is very useful.  Finally, I was thinking of added a comment system to my blog posts, but don't know if I should as it could be vunerable and shit like that and I also can't really be bothered seeing as no one would use it... On the plus side I got Jotit working on my UBT phone because it needed a bloody / at the end of the address, WHY??? idk it just does for some reason.  Anyway, that's it for today.<br/> Fly You High - DeaDvey<br/>", "Thu, 28 Dec 2023 20:41:39", ["custom_laptop.png", "nextcloud_maps.png"], ["Nextcloud", "Website", "VNC", "Laptop", "Maps"]],
["Merry Christmas!", "Merry Christmas everyone! Hope everyone is having a great day :), I had an interesting day, I got a Raspberry Pi 4 (4G version) and it's really cool, I already got <a href='https://supertuxkart.net/Main_Page'>Super Tux Kart</a> which is fun, I've also connected it to wifi and that's about it, I got a new keyboard which is way better than my old cheap stiff one, it seems to have helped my wpm, I got a massive power bank which has been charging for 3 hours now and has gone up 18% on the bank, meaning there is A LOT of total power in there :D  Finally, I've gotton a new monitor for a grand total of 3 which is nice, I can have firefox on one, music on the other and a game on the third, I love it. I also got a Tux sticker which is super nice and a mug whcih says 'number #0 programmer' lol.<br/>Fly You High - DeaDvey<br/><img src='https://i.pinimg.com/originals/3c/b3/91/3cb39177fe9f33771c961835ac85c754.png' height='200' alt='image of tux' /><img src='/images/supertuxkart.png' alt='Image of supertux kart' height='200'/>", "Mon, 25 Dec 2023 18:52:08", [], ["Christmas", "monitor", "keyboard", "sticker", "mug", "power bank"]],
["RSS feeds and Star Wars Squadrons", "Hey people (person(me)), I just updated my website to have an <a href='https://en.wikipedia.org/wiki/RSS'>RSS Feed</a> so that I can read them in Fluent Reader or Nextcloud News, the two RSS readers I use mostly, I cannot get them all to show up in Nextcloud News however, only the most recent one, maybe an issue with the formating? Ah well, I'll try troubleshoot that I guess.  Secondly, I recently got the game <a href='https://store.steampowered.com/app/1222730/STAR_WARS_Squadrons/'>Star Wars Squadrons</a> on my PC after already having played it on my PS4 and I was surprised at the poor reviews, I always found the game really fun and the integrated HUD really fun to use, guess I just am different lol, anyway<br/> Fly You High - DeaDvey<br/><img src='https://cdn.cloudflare.steamstatic.com/steam/apps/1222730/header.jpg?t=1662047498' />", "Sun, 24 Dec 2023 00:01:23", [], ["RSS", "Sqaudrons", "Star Wars", "News"]],
["Late December Update Before Christmas","Hey guys, so I have been trying out Nextcloud since I did the last blog and I really like it, it's very good, the calendar especially, I think I definately prefer it to Proton Drive and Calendar because it's way better intergreated in to apps and stuff, there's also apps for it on the Ubuntu Touch store, which lacks Proton apps, the notes are also great as is the RSS reader that I can sync.  Secondly, I have also began watching Attack on Titan again as my freind has been going on about it, I'm readig the Manga but it is so slow, so I'll probably keep watching the Animé which I like.  Christmas is in a few days and we break up tommorow which is pretty exiting and I'll see some family, I think I'm getting the <a href='https://www.raspberrypi.com/products/raspberry-pi-5/'>Raspberry Pi 5</a> which is cool.  Finally, I got the <a href='https://store.steampowered.com/app/582160/Assassins_Creed_Origins/'>Assassins Creed Origins game</a> which I already had on PS4 but now I have on Steam because it was on sale, but I can't get it to work so I'll have to figure that out over the weekend, anyway, that is probably it for today.<br/>Fly You High - DeaDvey<br/><img src='https://searx.be/image_proxy?url=https%3A%2F%2Fi.pinimg.com%2F236x%2Fc5%2F7f%2Fe1%2Fc57fe1d506c6a3aa53bd953199b7ea9f.jpg&h=60634c3b8432ca80d66386441593891a87a58ae6ec4810c40a64a665b0e677fc' height='200' alt='An image of Assassins Creed Origins' /><img src='https://upload.wikimedia.org/wikipedia/commons/9/98/23551-Raspberry-Pi-5-8G-feature.jpg' height='200' alt='An image of a Raspberry Pi 5'/>","Thu, 21 Dec 2023 12:00:00", [], ["Christmas", "Raspberry", "pi", "Nextcloud"]],
["I didn't like Wordpress","So... Yeah, I didn't like wordpress very much, it's pretty clunky and I don't have much control over the webpage, and it's kinda not that fun to use, I'm glad I tried it out though because I kind of know how to use it know I suppose, I might copy over the wordpress back over to this so I can use it myself for fun I suppose.","Mon, 11 Dec 2023 12:00:00", ["wordpress.png"], ["Wordpress", "html", "control"]],
["Test post2", "Testicy Test","Sun, 10 Dec 2023 12:00:00",[],["Test"]],
["Test post", "Testy test!","Sun, 10 Dec 2023 12:00:00",[],["Test"]]]

blogs = blogs.reverse();

if (typeof module !== 'undefined' && module.exports) {
	module.exports = blogs;
}

